{% if flag?(:darwin) %}
  @[Link(framework: "OpenGL")]
{% else %}
  @[Link("gl")]
{% end %}
lib LibGL
  BLEND_EQUATION = 32777

  FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 36048

  STENCIL_ATTACHMENT = 36128

  FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 36057

  FRAMEBUFFER_BINDING = 36006
end
