{% if flag?(:darwin) %}
  @[Link(framework: "OpenGL")]
{% else %}
  @[Link("gl")]
{% end %}
lib LibGL
  MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 35968

  MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 35978

  MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 35979

  UNSIGNED_NORMALIZED = 35863

  COPY_READ_BUFFER_BINDING = 36662

  COPY_READ_BUFFER = 36662

  COPY_WRITE_BUFFER_BINDING = 36663

  COPY_WRITE_BUFFER = 36663

  TRANSFORM_FEEDBACK_BINDING = 36389
end
